const $=s=>document.querySelector(s);const duration=55;let elapsed=0,playing=false,last=0,muted=false,audio=null;const shots=[...document.querySelectorAll('.shot')];
function initAudio(){if(audio)return;audio=new(window.AudioContext||window.webkitAudioContext)()}
function tone(freq,start,len,gain=.035,type='sine'){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type=type;g.gain.setValueAtTime(0,audio.currentTime+start);g.gain.linearRampToValueAtTime(gain,audio.currentTime+start+.02);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+start+len);o.connect(g).connect(audio.destination);o.start(audio.currentTime+start);o.stop(audio.currentTime+start+len)}
function cueSound(t){if(t===1){tone(659,0,.38);tone(784,.18,.38);tone(880,.36,.7)}if(t===8){tone(160,0,.65,.025,'sawtooth');tone(82,.42,1,.018)}if(t===16){tone(510,0,.08,.045,'square');tone(510,.18,.08,.04,'square')}if(t===32){tone(392,0,.12,.04);tone(392,.28,.12,.04);tone(294,.65,.45,.035)}if(t===40)tone(92,0,1.7,.026,'sawtooth');if(t===48){tone(110,0,3,.02);tone(440,.2,.55,.018)}}
function frame(ts){if(!playing)return;if(!last)last=ts;const prev=elapsed;elapsed+=Math.min(.1,(ts-last)/1000);last=ts;if(elapsed>=duration){elapsed=duration;playing=false;$('#toggle').textContent='↻'}shots.forEach((s,i)=>{const at=Number(s.dataset.at),next=i<shots.length-1?Number(shots[i+1].dataset.at):duration+1;s.classList.toggle('active',elapsed>=at&&elapsed<next)});$('#timeline-progress').style.width=`${elapsed/duration*100}%`;$('#time').textContent=`${fmt(elapsed)} / 00:55`;[1,8,16,32,40,48].forEach(t=>{if(prev<t&&elapsed>=t)cueSound(t)});if(playing)requestAnimationFrame(frame)}
function fmt(s){const n=Math.floor(s);return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function play(){initAudio();audio?.resume();if(elapsed>=duration)elapsed=0;playing=true;last=0;$('#toggle').textContent='Ⅱ';requestAnimationFrame(frame)}
function pause(){playing=false;$('#toggle').textContent='▶'}
$('#play').onclick=()=>{$('#cinema').classList.add('visible');$('#cinema').scrollIntoView({behavior:'smooth'});setTimeout(play,350)};$('#toggle').onclick=()=>playing?pause():play();$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'音 OFF':'音 ON';$('#sound').setAttribute('aria-pressed',String(!muted))};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
