const story=window.STORY_DATA;
const evidence=[
  ['01','障害・苦情受付票',7,'三件の申告と送信記録の不在。'],['02','鳴沢避難事故報告',19,'七名という結論と一人分の差。'],['03','防災子局保守点検票',31,'廃止設備に残された作業痕。'],['04','共有フォルダ操作履歴',37,'削除された監査履歴。'],['05','音声資料比較解析報告',25,'環境音は一致し、声は確定しない。'],['06','祭礼復元調査・聞き取り',19,'別年代の三つの原話。'],['07','寺院過去帳抄録',19,'七霊と八つ目に見える欄。'],['08','個別聴取記録比較',13,'同じ録音から異なる文章。'],['09','北嶺日報・調査記事',37,'確認された設備不正。'],['10','削除済み掲示板復元ログ',25,'怪談が具体化する時系列。'],['11','声送り祭パンフレット',31,'編集された由来と順路。'],['12','水城遼・掲載保留稿',25,'正しい断片を危険な順番で並べた稿。']
];
const $=s=>document.querySelector(s);let current=Math.max(0,Math.min(37,Number(localStorage.getItem('ub-episode')||0)));let font=Number(localStorage.getItem('ub-font')||18);
function escapeText(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function renderText(text){return text.split(/\n\s*\n/).map(block=>{const t=block.trim();if(!t)return'';if(t==='---')return'<div class="rule"></div>';if(t.startsWith('|')||/^[-*] /.test(t)||/^\d+\. /.test(t)||t.startsWith('>'))return`<div class="document-line">${escapeText(t.replace(/^>\s?/gm,''))}</div>`;return`<p>${escapeText(t).replace(/\n/g,'<br>')}</p>`}).join('')}
function render(){const ep=story.episodes[current];$('#episode-position').textContent=`EP.${String(current+1).padStart(2,'0')} / 38`;$('#episode-chapter').textContent=ep.chapter;$('#episode-title').textContent=ep.title;$('#story-text').innerHTML=renderText(ep.text);$('#previous').disabled=current===0;$('#next').disabled=current===37;const pct=Math.round((current/37)*100);$('#progress-value').textContent=`${pct}%`;document.querySelector('.progress-ring').style.setProperty('--p',`${pct*3.6}deg`);document.documentElement.style.setProperty('--reader-size',`${font}px`);localStorage.setItem('ub-episode',current);renderContext();document.title=`${ep.title}｜未登録放送 完全版`}
function renderContext(){const open=evidence.filter(x=>x[2]<=current+1);$('#context-evidence').innerHTML=(open.length?open.slice(-3):[['--','未開示',0,'本文の進行に応じて資料が表示されます。']]).map(x=>`<article><span>NS-A${x[0]}</span><p>${x[1]}<br>${x[3]}</p></article>`).join('')}
function go(n){current=Math.max(0,Math.min(37,n));render();$('#reader').scrollIntoView({behavior:'smooth'})}
$('#previous').onclick=()=>go(current-1);$('#next').onclick=()=>go(current+1);$('#start-reading').onclick=()=>go(0);$('#font-down').onclick=()=>{font=Math.max(15,font-1);localStorage.setItem('ub-font',font);render()};$('#font-up').onclick=()=>{font=Math.min(24,font+1);localStorage.setItem('ub-font',font);render()};$('#theme-toggle').onclick=()=>{document.body.classList.toggle('paper');localStorage.setItem('ub-paper',document.body.classList.contains('paper')?'1':'0')};if(localStorage.getItem('ub-paper')==='1')document.body.classList.add('paper');
const drawer=$('#drawer'),content=$('#drawer-content'),drawerTitle=$('#drawer-title');function openDrawer(type){if(type==='episodes'){drawerTitle.textContent='全38話';content.innerHTML=`<div class="episode-list">${story.episodes.map((e,i)=>`<button data-episode="${i}" class="${i===current?'current':''}"><small>EP.${String(i+1).padStart(2,'0')} / ${e.chapter}</small>${e.title}</button>`).join('')}</div>`;content.querySelectorAll('[data-episode]').forEach(b=>b.onclick=()=>{drawer.close();go(Number(b.dataset.episode))})}else if(type==='evidence'){drawerTitle.textContent='作中資料・全12点';content.innerHTML=`<div class="evidence-list">${evidence.map(x=>`<a href="https://nonamenonowork.github.io/narushiro-archive/archive/${x[0]}-${['incident-reception','narusawa-report','maintenance','shared-folder','audio-analysis','interview','temple-register','transcripts','newspaper','forum','brochure','unpublished-draft'][Number(x[0])-1]}.html"><span>NS-A${x[0]} / EP.${x[2]}</span><b>${x[1]}</b><p>${x[3]}</p></a>`).join('')}</div>`}else{$('#visual-section').scrollIntoView({behavior:'smooth'});return}drawer.showModal()}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.open));$('#drawer-close').onclick=()=>drawer.close();
const lightbox=$('#lightbox');document.querySelectorAll('.visual-card').forEach(b=>b.onclick=()=>{$('#lightbox-image').src=b.dataset.image;$('#lightbox-image').alt=b.dataset.alt;$('#lightbox-caption').textContent=b.dataset.alt;lightbox.showModal()});$('#lightbox-close').onclick=()=>lightbox.close();
window.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&!drawer.open&&!lightbox.open)go(current+1);if(e.key==='ArrowLeft'&&!drawer.open&&!lightbox.open)go(current-1)});render();
